import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { ToastrModule } from 'ngx-toastr';
import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';
import { AppModuleMaterials } from './app.module.materials';

import {
  // used in service
  ShowFormErrorsComponent, PhoneCallComponent, PhoneCallActionPopover,
  PrivateMessagingComponent, MemberLoginFormComponent, LoginOptionsComponent,
  // used in pages
  // HomeComponent,
  Page404Component, PageErrorComponent,
  LoginShellComponent,
  HLoaderComponent,
  ContactSearchModalComponent,
  CapturePhotoModalComponent,
  UploadPhotoMenuComponent,
  CallFailureModalComponent,
  DashboardHomeComponent,
  MaterialAlertComponent,
  MaterialActionAlertComponent,
  MaterialSnackBarComponent,
  PbxRepLinesComponent,
  CompanyComponent,
  EmployeesComponent,
  CompanyOverviewComponent,
  CreateCompanyComponent,
  CreatePbxLineComponent,
  InviteEmployeeComponent,
  CallQueueComponent,
  PbxLineComponent,
  PbxLineInformationComponent,
  PbxLineChatComponent,
  PbxLineQueueComponent,
  PbxLineCallComponent,
  PbxLineVideoComponent,
  PbxLineOutgoingCallDialog,
  PbxLinesComponent,
  PbxCustomerComponent,
  PbxSearchBoxComponent,
  PbxSearchComponent,
  PbxRepShellComponent,
  PbxEmployersComponent,
  OutgoingCallDialogComponent,
  EmployeeCompaniesComponent,
  GuestLoginFormComponent,
  RegisterFormComponent,
  FooterComponent,
  ProfileSummaryComponent,
  NavMenuComponent,
  ContactUsFormComponent,
  ContactComponent,
  ContactListComponent,
  ButtonAddContactComponent,
  SidenavToggleComponent,
  FormAddContactComponent,
  ImageSelectorComponent,
  PhotoCameraComponent,
  FormEditContactComponent,
  ContactCardComponent,
  IdCardComponent,
  IncomingPhoneCallComponent,
  PhoneListenerComponent,
  GlobalListenerComponent,
  GlobalPhoneListenerComponent,
  FormCreateCompanyComponent,
  FormEditCompanyComponent,
  CompanyLocationsComponent,
  CompanyPbxlineDetailsComponent,
  CompanyPbxlineRepsComponent,
  CompanyPhotosComponent,
  CompanyVideosComponent,
  EmployerAssignedPbxlineComponent,
  EmployerDetailsComponent,
  FormCompanyEmployeeAddComponent,
  FormCompanyEmployeeEditComponent,
  FormCompanyEmployeeInviteAddComponent,
  FormCompanyEmployeeInviteEditComponent,
  FormCompanyLocationAddComponent,
  FormCompanyPbxlineAddComponent,
  FormCompanyPbxlineEditComponent,
  FormCompanyPhotoAddComponent,
  FormCompanyVideoAddComponent,
  FormCompanyPbxlineRepAddComponent,
  CompanyPhotoComponent,
  ButtonAddCompanyPhotoComponent,
  FormCompanyLocationEditComponent,
  ButtonAddCompanyLocationComponent,
  ButtonAddCompanyVideoComponent,
  ButtonAddEmployeeInviteComponent,
  ButtonAddPbxlineComponent,
  CompanyLocationComponent,
  CompanyPbxlineComponent,
  EmployeeCardComponent,
  CompanyEmployeeInviteComponent,
  CompanyEmployeeComponent,
  PublicPbxlineComponent,
  PhoneRingerComponent,
  TextMessagingComponent,
  TextMessagingMessageComponent,
  PbxCustomerDetailsComponent,
  OtherRepsComponent,
  OtherRepComponent,
  FormGetInfoComponent,
  MeetingAttendeeComponent,
  FormAddAttendeeComponent,
  MeetingItemComponent,
  FormEditMeetingComponent,
  MeetingDetailsComponent,
  MeetingInviteComponent,
  FormNetcastAddComponent,
  FormNetcastEditComponent,
  ButtonAddNetcastComponent,
} from './components/index'
import {
  PageCanActivate,
  GuestCanActivate,
  MemberCanActivate,
  EmployeeCompaniesResolver
} from "./guards/index";
import {
  ContactService,
  SettingsService,
  VideoHelperService,
  ConfigService,
  SignalrService,
  JsHelperService,
  LocalStorageService,
  BlockCallService,
  UserService,
  PushService,
  PermissionsService,
  FlashMessageService,
  CapturePhotoService,
  MaterialsHelperService,
  PbxService,
  FormsErrorService,
  Service,
  MeetingService,
  NetcastService,
} from './services/index';
import { MapperService } from './services/mapper.service';

@NgModule({
  declarations: [
    AppComponent,
    // used in service
    ShowFormErrorsComponent,
    LoginOptionsComponent,
    MemberLoginFormComponent,
    PhoneCallComponent,
    PhoneCallActionPopover,
    PrivateMessagingComponent,
    // used in page
    // HomeComponent,
    Page404Component,
    PageErrorComponent,
    LoginShellComponent,
    HLoaderComponent,
    ContactSearchModalComponent,
    CapturePhotoModalComponent,
    UploadPhotoMenuComponent,
    CallFailureModalComponent,
    DashboardHomeComponent,
    MaterialAlertComponent,
    MaterialActionAlertComponent,
    MaterialSnackBarComponent,
    PbxRepLinesComponent,
    CompanyComponent,
    EmployeesComponent,
    CompanyOverviewComponent,
    CreateCompanyComponent,
    CreatePbxLineComponent,
    InviteEmployeeComponent,
    CallQueueComponent,
    PbxLineComponent,
    PbxLineInformationComponent,
    PbxLineChatComponent,
    PbxLineQueueComponent,
    PbxLineCallComponent,
    PbxLineVideoComponent,
    PbxLineOutgoingCallDialog,
    PbxLinesComponent,
    PbxCustomerComponent,
    PbxSearchBoxComponent,
    PbxSearchComponent,
    PbxRepShellComponent,
    PbxEmployersComponent,
    OutgoingCallDialogComponent,
    EmployeeCompaniesComponent,
    GuestLoginFormComponent,
    RegisterFormComponent,
    FooterComponent,
    ProfileSummaryComponent,
    NavMenuComponent,
    ContactUsFormComponent,
    ContactComponent,
    ContactListComponent,
    ButtonAddContactComponent,
    SidenavToggleComponent,
    FormAddContactComponent,
    ImageSelectorComponent,
    PhotoCameraComponent,
    FormEditContactComponent,
    ContactCardComponent,
    IdCardComponent,
    IncomingPhoneCallComponent,
    PhoneListenerComponent,
    GlobalListenerComponent,
    GlobalPhoneListenerComponent,
    FormCreateCompanyComponent,
    FormEditCompanyComponent,
    CompanyLocationsComponent,
    CompanyPbxlineDetailsComponent,
    CompanyPbxlineRepsComponent,
    CompanyPhotosComponent,
    CompanyVideosComponent,
    EmployerAssignedPbxlineComponent,
    EmployerDetailsComponent,
    FormCompanyEmployeeAddComponent,
    FormCompanyEmployeeEditComponent,
    FormCompanyEmployeeInviteAddComponent,
    FormCompanyEmployeeInviteEditComponent,
    FormCompanyLocationAddComponent,
    FormCompanyPbxlineAddComponent,
    FormCompanyPbxlineEditComponent,
    FormCompanyPhotoAddComponent,
    FormCompanyVideoAddComponent,
    FormCompanyPbxlineRepAddComponent,
    CompanyPhotoComponent,
    ButtonAddCompanyPhotoComponent,
    FormCompanyLocationEditComponent,
    ButtonAddCompanyLocationComponent,
    ButtonAddCompanyVideoComponent,
    ButtonAddEmployeeInviteComponent,
    ButtonAddPbxlineComponent,
    CompanyLocationComponent,
    CompanyPbxlineComponent,
    EmployeeCardComponent,
    CompanyEmployeeInviteComponent,
    CompanyEmployeeComponent,
    PublicPbxlineComponent,
    PhoneRingerComponent,
    TextMessagingComponent,
    TextMessagingMessageComponent,
    PbxCustomerDetailsComponent,
    OtherRepsComponent,
    OtherRepComponent,
    FormGetInfoComponent,
    MeetingAttendeeComponent,
    FormAddAttendeeComponent,
    MeetingItemComponent,
    FormEditMeetingComponent,
    MeetingDetailsComponent,
    MeetingInviteComponent,
    FormNetcastAddComponent,
    FormNetcastEditComponent,
    ButtonAddNetcastComponent,
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    FormsModule,
    ReactiveFormsModule,
    AppModuleMaterials,
    AppRoutingModule,
    HttpClientModule,
    ToastrModule.forRoot(
      {
        positionClass: 'toast-top-center',
        messageClass: 'is-open-sans',
        titleClass: 'is-open-sans',
        timeOut: 6400
      }
    ),
  ],
  providers: [
    { provide: 'ORIGIN_URL', useValue: location.origin },
    ContactService,
    SettingsService,
    VideoHelperService,
    ConfigService,
    SignalrService,
    JsHelperService,
    LocalStorageService,
    BlockCallService,
    UserService,
    PushService,
    PermissionsService,
    FlashMessageService,
    CapturePhotoService,
    MaterialsHelperService,
    PbxService,
    FormsErrorService,
    Service,
    PageCanActivate,
    GuestCanActivate,
    MemberCanActivate,
    EmployeeCompaniesResolver,
    MeetingService,
    NetcastService,
    MapperService,
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
